name: Deploy MkDocs su GitHub Pages

on:
  push:
    branches:
      - main # Cambia in 'master' se il tuo branch principale si chiama così

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-callouts # Installa tema e plugin usati in mkdocs.yml
      - run: mkdocs gh-deploy --force